behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    enable_stamped_cmd_vel: true    
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0 #rate at which the control loop
    behavior_plugins: ["spin", "backup", "wait"]
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.3
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

    spin:
      plugin: "nav2_behaviors::Spin"

    backup:
      plugin: "nav2_behaviors::BackUp"

    wait:
      plugin: "nav2_behaviors::Wait"

