bt_navigator: 
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /bumperbot_controller/odom
    transform_tolerance: 0.3
    default_server_timeout: 1000
    bt_loop_duration: 10
    wait_for_service_timeout: 1000
    default_nav_to_pose_bt_xml: "/home/nel/bumperbo_ws/src/bumperbot_navigation/behaviour_tree/simple_navigation_w_replanning_and_recoveries.xml"
    default_nav_through_poses_bt_xml: "/home/nel/bumperbo_ws/src/bumperbot_navigation/behaviour_tree/simple_navigation.xml"